// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>De.AHoerstemeier.Tambon</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace De.AHoerstemeier.Tambon
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute("electiondata", Namespace = "http://hoerstemeier.com/tambon/", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ElectionData", Namespace = "http://hoerstemeier.com/tambon/")]
    public partial class ElectionData
    {

        private List<Party> partiesField;

        private ConstituencyEntity entityField;

        /// <summary>
        /// ElectionData class constructor
        /// </summary>
        public ElectionData()
        {
            this.entityField = new ConstituencyEntity();
            this.partiesField = new List<Party>();
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("party", IsNullable = false)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<Party> parties
        {
            get
            {
                return this.partiesField;
            }
            set
            {
                this.partiesField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConstituencyEntity entity
        {
            get
            {
                return this.entityField;
            }
            set
            {
                this.entityField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Party", Namespace = "http://hoerstemeier.com/tambon/")]
    public partial class Party
    {

        private string nameField;

        private string englishField;

        private string idField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string english
        {
            get
            {
                return this.englishField;
            }
            set
            {
                this.englishField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ConstituencyEntity", Namespace = "http://hoerstemeier.com/tambon/")]
    public partial class ConstituencyEntity : EntityBase
    {

        private List<ConstituencyEntity> entityField;

        private List<Constituency> constituenciesField;

        private Election electionField;

        /// <summary>
        /// ConstituencyEntity class constructor
        /// </summary>
        public ConstituencyEntity()
        {
            this.electionField = new Election();
            this.constituenciesField = new List<Constituency>();
            this.entityField = new List<ConstituencyEntity>();
        }

        [System.Xml.Serialization.XmlElementAttribute("entity", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<ConstituencyEntity> entity
        {
            get
            {
                return this.entityField;
            }
            set
            {
                this.entityField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("constituency", IsNullable = false)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<Constituency> constituencies
        {
            get
            {
                return this.constituenciesField;
            }
            set
            {
                this.constituenciesField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Election election
        {
            get
            {
                return this.electionField;
            }
            set
            {
                this.electionField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Constituency", Namespace = "http://hoerstemeier.com/tambon/")]
    public partial class Constituency
    {

        private List<EntityBase> itemsField;

        private List<Election> electionField;

        private List<ByElection> byelectionField;

        private byte indexField;

        private byte numberofseatsField;

        private string commentField;

        public Constituency()
        {
            this.byelectionField = new List<ByElection>();
            this.electionField = new List<Election>();
            this.itemsField = new List<EntityBase>();
            this.numberofseatsField = ((byte)(1));
        }

        [System.Xml.Serialization.XmlElementAttribute("include", typeof(EntityInclude), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("includesub", typeof(EntityIncludeSub), Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityBase> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("election", Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<Election> election
        {
            get
            {
                return this.electionField;
            }
            set
            {
                this.electionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("byelection", Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<ByElection> byelection
        {
            get
            {
                return this.byelectionField;
            }
            set
            {
                this.byelectionField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(byte), "1")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte numberofseats
        {
            get
            {
                return this.numberofseatsField;
            }
            set
            {
                this.numberofseatsField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EntityInclude", Namespace = "http://hoerstemeier.com/tambon/")]
    public partial class EntityInclude : EntityBase
    {

        private List<EntityInExclude> excludeField;

        /// <summary>
        /// EntityInclude class constructor
        /// </summary>
        public EntityInclude()
        {
            this.excludeField = new List<EntityInExclude>();
        }

        [System.Xml.Serialization.XmlElementAttribute("exclude", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityInExclude> exclude
        {
            get
            {
                return this.excludeField;
            }
            set
            {
                this.excludeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EntityInExclude", Namespace = "http://hoerstemeier.com/tambon/")]
    public partial class EntityInExclude : EntityBase
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EntityIncludeSub", Namespace = "http://hoerstemeier.com/tambon/")]
    public partial class EntityIncludeSub : EntityBase
    {

        private List<EntityInExclude> includeField;

        /// <summary>
        /// EntityIncludeSub class constructor
        /// </summary>
        public EntityIncludeSub()
        {
            this.includeField = new List<EntityInExclude>();
        }

        [System.Xml.Serialization.XmlElementAttribute("include", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityInExclude> include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Election", Namespace = "http://hoerstemeier.com/tambon/")]
    public partial class Election
    {

        private List<PartyCandidateList> partylistField;

        private PartyListResult partylistresultField;

        private CandidateList candidatesField;

        private List<GazetteReference> gazetterefField;

        private System.DateTime dateField;

        private bool dateFieldSpecified;

        private ElectionType typeField;

        private bool typeFieldSpecified;

        /// <summary>
        /// Election class constructor
        /// </summary>
        public Election()
        {
            this.gazetterefField = new List<GazetteReference>();
            this.candidatesField = new CandidateList();
            this.partylistresultField = new PartyListResult();
            this.partylistField = new List<PartyCandidateList>();
        }

        [System.Xml.Serialization.XmlElementAttribute("partylist", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<PartyCandidateList> partylist
        {
            get
            {
                return this.partylistField;
            }
            set
            {
                this.partylistField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartyListResult partylistresult
        {
            get
            {
                return this.partylistresultField;
            }
            set
            {
                this.partylistresultField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CandidateList candidates
        {
            get
            {
                return this.candidatesField;
            }
            set
            {
                this.candidatesField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("gazetteref", Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<GazetteReference> gazetteref
        {
            get
            {
                return this.gazetterefField;
            }
            set
            {
                this.gazetterefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool dateSpecified
        {
            get
            {
                return this.dateFieldSpecified;
            }
            set
            {
                this.dateFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectionType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PartyCandidateList", Namespace = "http://hoerstemeier.com/tambon/")]
    public partial class PartyCandidateList
    {

        private List<PartyCandidateListEntry> candidateField;

        private string partyField;

        /// <summary>
        /// PartyCandidateList class constructor
        /// </summary>
        public PartyCandidateList()
        {
            this.candidateField = new List<PartyCandidateListEntry>();
        }

        [System.Xml.Serialization.XmlElementAttribute("candidate", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<PartyCandidateListEntry> candidate
        {
            get
            {
                return this.candidateField;
            }
            set
            {
                this.candidateField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string party
        {
            get
            {
                return this.partyField;
            }
            set
            {
                this.partyField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PartyCandidateListEntry", Namespace = "http://hoerstemeier.com/tambon/")]
    public partial class PartyCandidateListEntry : Candidate
    {

        private string indexField;

        private System.DateTime beginField;

        private bool beginFieldSpecified;

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime begin
        {
            get
            {
                return this.beginField;
            }
            set
            {
                this.beginField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool beginSpecified
        {
            get
            {
                return this.beginFieldSpecified;
            }
            set
            {
                this.beginFieldSpecified = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PartyCandidateListEntry))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CandidateListEntry))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Candidate", Namespace = "http://hoerstemeier.com/tambon/")]
    public partial class Candidate
    {

        private List<GazetteReference> gazetterefField;

        private string partyField;

        private string nameField;

        private string titleField;

        private string englishField;

        private ElectionStatus statusField;

        private bool statusFieldSpecified;

        private string commentField;

        private System.DateTime endField;

        private bool endFieldSpecified;

        private ByElectionReason endreasonField;

        private bool endreasonFieldSpecified;

        /// <summary>
        /// Candidate class constructor
        /// </summary>
        public Candidate()
        {
            this.gazetterefField = new List<GazetteReference>();
        }

        [System.Xml.Serialization.XmlElementAttribute("gazetteref", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<GazetteReference> gazetteref
        {
            get
            {
                return this.gazetterefField;
            }
            set
            {
                this.gazetterefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string party
        {
            get
            {
                return this.partyField;
            }
            set
            {
                this.partyField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string english
        {
            get
            {
                return this.englishField;
            }
            set
            {
                this.englishField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectionStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime end
        {
            get
            {
                return this.endField;
            }
            set
            {
                this.endField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool endSpecified
        {
            get
            {
                return this.endFieldSpecified;
            }
            set
            {
                this.endFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ByElectionReason endreason
        {
            get
            {
                return this.endreasonField;
            }
            set
            {
                this.endreasonField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool endreasonSpecified
        {
            get
            {
                return this.endreasonFieldSpecified;
            }
            set
            {
                this.endreasonFieldSpecified = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    public enum ElectionStatus
    {

        /// <remarks/>
        elected,

        /// <remarks/>
        pending,

        /// <remarks/>
        redcard,

        /// <remarks/>
        yellowcard,

        /// <remarks/>
        disqualified,

        /// <remarks/>
        resigned,

        /// <remarks/>
        died,

        /// <remarks/>
        moveup,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    public enum ByElectionReason
    {

        /// <remarks/>
        redcard,

        /// <remarks/>
        yellowcard,

        /// <remarks/>
        resignation,

        /// <remarks/>
        bankruptcy,

        /// <remarks/>
        conviction,

        /// <remarks/>
        death,

        /// <remarks/>
        disqualification,

        /// <remarks/>
        other,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CandidateListEntry", Namespace = "http://hoerstemeier.com/tambon/")]
    public partial class CandidateListEntry : Candidate
    {

        private string idField;

        private string votesField;

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string votes
        {
            get
            {
                return this.votesField;
            }
            set
            {
                this.votesField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PartyListResult", Namespace = "http://hoerstemeier.com/tambon/")]
    public partial class PartyListResult
    {

        private List<PartyListResultEntry> partyField;

        private string eligiblevoterField;

        private string invalidvotesField;

        private string abstainvotesField;

        /// <summary>
        /// PartyListResult class constructor
        /// </summary>
        public PartyListResult()
        {
            this.partyField = new List<PartyListResultEntry>();
        }

        [System.Xml.Serialization.XmlElementAttribute("party", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<PartyListResultEntry> party
        {
            get
            {
                return this.partyField;
            }
            set
            {
                this.partyField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eligiblevoter
        {
            get
            {
                return this.eligiblevoterField;
            }
            set
            {
                this.eligiblevoterField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invalidvotes
        {
            get
            {
                return this.invalidvotesField;
            }
            set
            {
                this.invalidvotesField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string abstainvotes
        {
            get
            {
                return this.abstainvotesField;
            }
            set
            {
                this.abstainvotesField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PartyListResultEntry", Namespace = "http://hoerstemeier.com/tambon/")]
    public partial class PartyListResultEntry
    {

        private string idField;

        private string votesField;

        private string seatsField;

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string votes
        {
            get
            {
                return this.votesField;
            }
            set
            {
                this.votesField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string seats
        {
            get
            {
                return this.seatsField;
            }
            set
            {
                this.seatsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CandidateList", Namespace = "http://hoerstemeier.com/tambon/")]
    public partial class CandidateList
    {

        private List<CandidateListEntry> candidateField;

        private string eligiblevoterField;

        private string invalidvotesField;

        private string abstainvotesField;

        private string commentField;

        /// <summary>
        /// CandidateList class constructor
        /// </summary>
        public CandidateList()
        {
            this.candidateField = new List<CandidateListEntry>();
        }

        [System.Xml.Serialization.XmlElementAttribute("candidate", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<CandidateListEntry> candidate
        {
            get
            {
                return this.candidateField;
            }
            set
            {
                this.candidateField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eligiblevoter
        {
            get
            {
                return this.eligiblevoterField;
            }
            set
            {
                this.eligiblevoterField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invalidvotes
        {
            get
            {
                return this.invalidvotesField;
            }
            set
            {
                this.invalidvotesField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string abstainvotes
        {
            get
            {
                return this.abstainvotesField;
            }
            set
            {
                this.abstainvotesField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    public enum ElectionType
    {

        /// <remarks/>
        Parliament,

        /// <remarks/>
        Senate,

        /// <remarks/>
        PAOChairman,

        /// <remarks/>
        PAOCouncil,

        /// <remarks/>
        TAOMayor,

        /// <remarks/>
        TAOCouncil,

        /// <remarks/>
        Mayor,

        /// <remarks/>
        ThesabanCouncil,

        /// <remarks/>
        BangkokGovernor,

        /// <remarks/>
        BangkokCouncil,

        /// <remarks/>
        BangkokDistrictCouncil,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ByElection", Namespace = "http://hoerstemeier.com/tambon/")]
    public partial class ByElection
    {

        private CandidateList candidatesField;

        private List<GazetteReference> gazetterefField;

        private System.DateTime dateField;

        private bool dateFieldSpecified;

        private ElectionType typeField;

        private bool typeFieldSpecified;

        private ByElectionReason reasonField;

        private bool reasonFieldSpecified;

        private string commentField;

        /// <summary>
        /// ByElection class constructor
        /// </summary>
        public ByElection()
        {
            this.gazetterefField = new List<GazetteReference>();
            this.candidatesField = new CandidateList();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CandidateList candidates
        {
            get
            {
                return this.candidatesField;
            }
            set
            {
                this.candidatesField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("gazetteref", Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<GazetteReference> gazetteref
        {
            get
            {
                return this.gazetterefField;
            }
            set
            {
                this.gazetterefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool dateSpecified
        {
            get
            {
                return this.dateFieldSpecified;
            }
            set
            {
                this.dateFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectionType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ByElectionReason reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool reasonSpecified
        {
            get
            {
                return this.reasonFieldSpecified;
            }
            set
            {
                this.reasonFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ConstituencyList", Namespace = "http://hoerstemeier.com/tambon/")]
    public partial class ConstituencyList
    {

        private List<Constituency> constituencyField;

        /// <summary>
        /// ConstituencyList class constructor
        /// </summary>
        public ConstituencyList()
        {
            this.constituencyField = new List<Constituency>();
        }

        [System.Xml.Serialization.XmlElementAttribute("constituency", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<Constituency> constituency
        {
            get
            {
                return this.constituencyField;
            }
            set
            {
                this.constituencyField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PartyList", Namespace = "http://hoerstemeier.com/tambon/")]
    public partial class PartyList
    {

        private List<Party> partyField;

        /// <summary>
        /// PartyList class constructor
        /// </summary>
        public PartyList()
        {
            this.partyField = new List<Party>();
        }

        [System.Xml.Serialization.XmlElementAttribute("party", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<Party> party
        {
            get
            {
                return this.partyField;
            }
            set
            {
                this.partyField = value;
            }
        }
    }
}
