// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.3.27461
//    <NameSpace>De.AHoerstemeier.Tambon</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace De.AHoerstemeier.Tambon
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SocialWebLink", Namespace = "http://hoerstemeier.com/tambon/", IsReference = true)]
    public partial class SocialWebLink
    {

        private SocialWebStatus statusField;

        private string commentField;

        private string valueField;

        /// <summary>
        /// Creates a new instance of SocialWebLink.
        /// </summary>
        public SocialWebLink()
        {
            this.statusField = SocialWebStatus.unknown;
        }

        /// <summary>
        /// Auto generated comment tag to suppress XML code documentation warning.
        /// </summary>
        /// <value>
        /// Auto generated value tag to suppress XML code documentation warning.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(SocialWebStatus.unknown)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SocialWebStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <summary>
        /// Auto generated comment tag to suppress XML code documentation warning.
        /// </summary>
        /// <value>
        /// Auto generated value tag to suppress XML code documentation warning.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <summary>
        /// Auto generated comment tag to suppress XML code documentation warning.
        /// </summary>
        /// <value>
        /// Auto generated value tag to suppress XML code documentation warning.
        /// </value>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <summary>
    /// Status of a social web account.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = false)]
    public enum SocialWebStatus
    {

        /// <summary>
        /// Current status not known.
        /// </summary>
        unknown,

        /// <summary>
        /// Currently in use.
        /// </summary>
        active,

        /// <summary>
        /// Not used for a long time, at least one year in no activity.
        /// </summary>
        inactive,

        /// <summary>
        /// Account no longer accessible.
        /// </summary>
        offline,
    }

    /// <summary>
    /// List of the social web sites where the entity is present.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SocialWebLinks", Namespace = "http://hoerstemeier.com/tambon/", IsReference = true)]
    public partial class SocialWebLinks
    {

        private string facebookField;

        private SocialWebLink twitterField;

        private SocialWebLink googleplusField;

        private List<MyUri> blogField;

        /// <summary>
        /// Creates a new instance of SocialWebLinks.
        /// </summary>
        public SocialWebLinks()
        {
            this.blogField = new List<MyUri>();
            this.googleplusField = new SocialWebLink();
            this.twitterField = new SocialWebLink();
        }

        /// <summary>
        /// URL of the user account or page in facebook.
        /// </summary>
        /// <value>
        /// The facebook.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string facebook
        {
            get
            {
                return this.facebookField;
            }
            set
            {
                this.facebookField = value;
            }
        }

        /// <summary>
        /// Twitter user name.
        /// </summary>
        /// <value>
        /// The twitter.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SocialWebLink twitter
        {
            get
            {
                return this.twitterField;
            }
            set
            {
                this.twitterField = value;
            }
        }

        /// <summary>
        /// Numerical code of the user or page.
        /// </summary>
        /// <value>
        /// The googleplus.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SocialWebLink googleplus
        {
            get
            {
                return this.googleplusField;
            }
            set
            {
                this.googleplusField = value;
            }
        }

        /// <summary>
        /// Blog URL.
        /// </summary>
        /// <value>
        /// The blog.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute("blog", Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<MyUri> blog
        {
            get
            {
                return this.blogField;
            }
            set
            {
                this.blogField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "OfficialEntry", Namespace = "http://hoerstemeier.com/tambon/", IsReference = true)]
    public partial class OfficialEntry
    {

        private Election electionField;

        private OfficialType titleField;

        private int indexField;

        private bool indexFieldSpecified;

        private string nameField;

        private string englishField;

        private System.DateTime beginField;

        private bool beginFieldSpecified;

        private string endyearField;

        private string beginyearField;

        private System.DateTime endField;

        private bool endFieldSpecified;

        private bool actingField;

        private bool actingFieldSpecified;

        private string inofficeField;

        private string commentField;

        private OfficialBeginType beginreasonField;

        private OfficialEndType endreasonField;

        private int mubanField;

        private bool mubanFieldSpecified;

        /// <summary>
        /// Creates a new instance of OfficialEntry.
        /// </summary>
        public OfficialEntry()
        {
            this.beginreasonField = OfficialBeginType.Unknown;
            this.endreasonField = OfficialEndType.Unknown;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Election election
        {
            get
            {
                return this.electionField;
            }
            set
            {
                this.electionField = value;
            }
        }

        /// <summary>
        /// Type of official.
        /// </summary>
        /// <value>
        /// The title.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OfficialType title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <summary>
        /// Running number, if known.
        /// </summary>
        /// <value>
        /// The index.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <summary>
        /// Auto generated comment tag to suppress XML code documentation warning.
        /// </summary>
        /// <value>
        /// Auto generated value tag to suppress XML code documentation warning.
        /// </value>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indexSpecified
        {
            get
            {
                return this.indexFieldSpecified;
            }
            set
            {
                this.indexFieldSpecified = value;
            }
        }

        /// <summary>
        /// Name in Thai script, not including titles.
        /// </summary>
        /// <value>
        /// The name.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <summary>
        /// Transcription of name to English.
        /// </summary>
        /// <value>
        /// The english.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string english
        {
            get
            {
                return this.englishField;
            }
            set
            {
                this.englishField = value;
            }
        }

        /// <summary>
        /// Begin of term.
        /// </summary>
        /// <value>
        /// The begin.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime begin
        {
            get
            {
                return this.beginField;
            }
            set
            {
                this.beginField = value;
            }
        }

        /// <summary>
        /// Auto generated comment tag to suppress XML code documentation warning.
        /// </summary>
        /// <value>
        /// Auto generated value tag to suppress XML code documentation warning.
        /// </value>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool beginSpecified
        {
            get
            {
                return this.beginFieldSpecified;
            }
            set
            {
                this.beginFieldSpecified = value;
            }
        }

        /// <summary>
        /// End of term.
        /// </summary>
        /// <value>
        /// The endyear.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "gYear")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string endyear
        {
            get
            {
                return this.endyearField;
            }
            set
            {
                this.endyearField = value;
            }
        }

        /// <summary>
        /// Begin of term.
        /// </summary>
        /// <value>
        /// The beginyear.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "gYear")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string beginyear
        {
            get
            {
                return this.beginyearField;
            }
            set
            {
                this.beginyearField = value;
            }
        }

        /// <summary>
        /// End of term.
        /// </summary>
        /// <value>
        /// The end.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime end
        {
            get
            {
                return this.endField;
            }
            set
            {
                this.endField = value;
            }
        }

        /// <summary>
        /// Auto generated comment tag to suppress XML code documentation warning.
        /// </summary>
        /// <value>
        /// Auto generated value tag to suppress XML code documentation warning.
        /// </value>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool endSpecified
        {
            get
            {
                return this.endFieldSpecified;
            }
            set
            {
                this.endFieldSpecified = value;
            }
        }

        /// <summary>
        /// Acting or fully installed office leader.
        /// </summary>
        /// <value>
        /// The acting.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool acting
        {
            get
            {
                return this.actingField;
            }
            set
            {
                this.actingField = value;
            }
        }

        /// <summary>
        /// Auto generated comment tag to suppress XML code documentation warning.
        /// </summary>
        /// <value>
        /// Auto generated value tag to suppress XML code documentation warning.
        /// </value>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool actingSpecified
        {
            get
            {
                return this.actingFieldSpecified;
            }
            set
            {
                this.actingFieldSpecified = value;
            }
        }

        /// <summary>
        /// Year official was in office, used if being/end of term is not known.
        /// </summary>
        /// <value>
        /// The inoffice.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "gYear")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string inoffice
        {
            get
            {
                return this.inofficeField;
            }
            set
            {
                this.inofficeField = value;
            }
        }

        /// <summary>
        /// Comments for information not covered in the formal fields.
        /// </summary>
        /// <value>
        /// The comment.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <summary>
        /// Reason why left office.
        /// </summary>
        /// <value>
        /// The beginreason.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(OfficialBeginType.Unknown)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OfficialBeginType beginreason
        {
            get
            {
                return this.beginreasonField;
            }
            set
            {
                this.beginreasonField = value;
            }
        }

        /// <summary>
        /// Reason why left office.
        /// </summary>
        /// <value>
        /// The endreason.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(OfficialEndType.Unknown)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OfficialEndType endreason
        {
            get
            {
                return this.endreasonField;
            }
            set
            {
                this.endreasonField = value;
            }
        }

        /// <summary>
        /// Only for subdistrict headman (Kamnan), Muban number where he/she is also village headman.
        /// </summary>
        /// <value>
        /// The muban.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int muban
        {
            get
            {
                return this.mubanField;
            }
            set
            {
                this.mubanField = value;
            }
        }

        /// <summary>
        /// Auto generated comment tag to suppress XML code documentation warning.
        /// </summary>
        /// <value>
        /// Auto generated value tag to suppress XML code documentation warning.
        /// </value>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool mubanSpecified
        {
            get
            {
                return this.mubanFieldSpecified;
            }
            set
            {
                this.mubanFieldSpecified = value;
            }
        }
    }

    /// <summary>
    /// Ways how an official can enter the office.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = false)]
    public enum OfficialBeginType
    {

        /// <summary>
        /// Elected, not further specified if directly or indirectly.
        /// </summary>
        Elected,

        /// <summary>
        /// Elected directly by the population.
        /// </summary>
        ElectedDirectly,

        /// <summary>
        /// Elected from council.
        /// </summary>
        ElectedByCouncil,

        /// <summary>
        /// Having position because of another official position held by the person.
        /// </summary>
        ExOfficio,

        /// <summary>
        /// Appointed by a superior administrative unit.
        /// </summary>
        Appointed,

        /// <summary>
        /// No specified reason.
        /// </summary>
        Unknown,
    }

    /// <summary>
    /// Reasons why an official left office.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = false)]
    public enum OfficialEndType
    {

        /// <summary>
        /// End of term.
        /// </summary>
        EndOfTerm,

        /// <summary>
        /// Transferred to another office.
        /// </summary>
        Transfer,

        /// <summary>
        /// Reaching retirement age (เกษียณอายุราชการ).
        /// </summary>
        Retired,

        /// <summary>
        /// Resigned from office.
        /// </summary>
        Resigned,

        /// <summary>
        /// Died while being office holder.
        /// </summary>
        Death,

        /// <summary>
        /// Removed from post by higher authorities.
        /// </summary>
        Removed,

        /// <summary>
        /// No specified reason.
        /// </summary>
        Unknown,
    }

    /// <summary>
    /// List of leaders of the administrative entity.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "OfficialList", Namespace = "http://hoerstemeier.com/tambon/", IsReference = true)]
    public partial class OfficialList
    {

        private List<OfficialEntry> officialField;

        private string sourceField;

        /// <summary>
        /// Creates a new instance of OfficialList.
        /// </summary>
        public OfficialList()
        {
            this.officialField = new List<OfficialEntry>();
        }

        [System.Xml.Serialization.XmlElementAttribute("official", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<OfficialEntry> official
        {
            get
            {
                return this.officialField;
            }
            set
            {
                this.officialField = value;
            }
        }

        /// <summary>
        /// Source of the main part of the list.
        /// </summary>
        /// <value>
        /// The source.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
    }

    /// <summary>
    /// Term of the council of the administrative entity.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CouncilTerm", Namespace = "http://hoerstemeier.com/tambon/", IsReference = true)]
    public partial class CouncilTerm
    {

        private List<OfficialEntry> officialField;

        private Election electionField;

        private System.DateTime beginField;

        private bool beginFieldSpecified;

        private System.DateTime endField;

        private bool endFieldSpecified;

        /// <summary>
        /// Creates a new instance of CouncilTerm.
        /// </summary>
        public CouncilTerm()
        {
            this.officialField = new List<OfficialEntry>();
        }

        [System.Xml.Serialization.XmlElementAttribute("official", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<OfficialEntry> official
        {
            get
            {
                return this.officialField;
            }
            set
            {
                this.officialField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Election election
        {
            get
            {
                return this.electionField;
            }
            set
            {
                this.electionField = value;
            }
        }

        /// <summary>
        /// Begin of term.
        /// </summary>
        /// <value>
        /// The begin.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime begin
        {
            get
            {
                return this.beginField;
            }
            set
            {
                this.beginField = value;
            }
        }

        /// <summary>
        /// Auto generated comment tag to suppress XML code documentation warning.
        /// </summary>
        /// <value>
        /// Auto generated value tag to suppress XML code documentation warning.
        /// </value>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool beginSpecified
        {
            get
            {
                return this.beginFieldSpecified;
            }
            set
            {
                this.beginFieldSpecified = value;
            }
        }

        /// <summary>
        /// End of term.
        /// </summary>
        /// <value>
        /// The end.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime end
        {
            get
            {
                return this.endField;
            }
            set
            {
                this.endField = value;
            }
        }

        /// <summary>
        /// Auto generated comment tag to suppress XML code documentation warning.
        /// </summary>
        /// <value>
        /// Auto generated value tag to suppress XML code documentation warning.
        /// </value>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool endSpecified
        {
            get
            {
                return this.endFieldSpecified;
            }
            set
            {
                this.endFieldSpecified = value;
            }
        }
    }

    /// <summary>
    /// List of council terms of the administrative entity.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CouncilList", Namespace = "http://hoerstemeier.com/tambon/", IsReference = true)]
    public partial class CouncilList
    {

        private List<CouncilTerm> termField;

        /// <summary>
        /// Creates a new instance of CouncilList.
        /// </summary>
        public CouncilList()
        {
            this.termField = new List<CouncilTerm>();
        }

        [System.Xml.Serialization.XmlElementAttribute("term", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<CouncilTerm> term
        {
            get
            {
                return this.termField;
            }
            set
            {
                this.termField = value;
            }
        }
    }

    /// <summary>
    /// Village (Muban) part of address.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ThaiAddressVillage", Namespace = "http://hoerstemeier.com/tambon/", IsReference = true)]
    public partial class ThaiAddressVillage
    {

        private string nameField;

        private uint numberField;

        /// <summary>
        /// Name of the village.
        /// </summary>
        /// <value>
        /// The name.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <summary>
        /// Number of the village.
        /// </summary>
        /// <value>
        /// The number.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }

    /// <summary>
    /// Subdistrict (Tambon/Khet) part of address.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ThaiAddressTambon", Namespace = "http://hoerstemeier.com/tambon/", IsReference = true)]
    public partial class ThaiAddressTambon
    {

        private string nameField;

        private uint geocodeField;

        /// <summary>
        /// Name of subdistrict.
        /// </summary>
        /// <value>
        /// The name.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <summary>
        /// Geocode of district.
        /// </summary>
        /// <value>
        /// The geocode.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint geocode
        {
            get
            {
                return this.geocodeField;
            }
            set
            {
                this.geocodeField = value;
            }
        }
    }

    /// <summary>
    /// Address in Thailand
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ThaiAddress", Namespace = "http://hoerstemeier.com/tambon/", IsReference = true)]
    public partial class ThaiAddress
    {

        private ThaiAddressVillage villageField;

        private string plotField;

        private ThaiAddressTambon tambonField;

        private string streetField;

        private uint postcodeField;

        private bool postcodeFieldSpecified;

        /// <summary>
        /// Creates a new instance of ThaiAddress.
        /// </summary>
        public ThaiAddress()
        {
            this.tambonField = new ThaiAddressTambon();
            this.villageField = new ThaiAddressVillage();
        }

        /// <summary>
        /// Village part of address.
        /// </summary>
        /// <value>
        /// The village.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThaiAddressVillage village
        {
            get
            {
                return this.villageField;
            }
            set
            {
                this.villageField = value;
            }
        }

        /// <summary>
        /// Plot number/identifier.
        /// </summary>
        /// <value>
        /// The plot.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string plot
        {
            get
            {
                return this.plotField;
            }
            set
            {
                this.plotField = value;
            }
        }

        /// <summary>
        /// Subdistrict part of address.
        /// </summary>
        /// <value>
        /// The tambon.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThaiAddressTambon tambon
        {
            get
            {
                return this.tambonField;
            }
            set
            {
                this.tambonField = value;
            }
        }

        /// <summary>
        /// Street name and number.
        /// </summary>
        /// <value>
        /// The street.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }

        /// <summary>
        /// Postal code
        /// </summary>
        /// <value>
        /// The postcode.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }

        /// <summary>
        /// Auto generated comment tag to suppress XML code documentation warning.
        /// </summary>
        /// <value>
        /// Auto generated value tag to suppress XML code documentation warning.
        /// </value>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool postcodeSpecified
        {
            get
            {
                return this.postcodeFieldSpecified;
            }
            set
            {
                this.postcodeFieldSpecified = value;
            }
        }
    }

    /// <summary>
    /// List of former locations of the office.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "OldLocation", Namespace = "http://hoerstemeier.com/tambon/", IsReference = true)]
    public partial class OldLocation
    {

        private Point pointField;

        private ThaiAddress addressField;

        private System.DateTime endField;

        private bool endFieldSpecified;

        private string commentField;

        /// <summary>
        /// Creates a new instance of OldLocation.
        /// </summary>
        public OldLocation()
        {
            this.addressField = new ThaiAddress();
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.w3.org/2003/01/geo/wgs84_pos#", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Point Point
        {
            get
            {
                return this.pointField;
            }
            set
            {
                this.pointField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThaiAddress address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <summary>
        /// Date the office was closed at that location.
        /// </summary>
        /// <value>
        /// The end.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime end
        {
            get
            {
                return this.endField;
            }
            set
            {
                this.endField = value;
            }
        }

        /// <summary>
        /// Auto generated comment tag to suppress XML code documentation warning.
        /// </summary>
        /// <value>
        /// Auto generated value tag to suppress XML code documentation warning.
        /// </value>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool endSpecified
        {
            get
            {
                return this.endFieldSpecified;
            }
            set
            {
                this.endFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
    }

    /// <summary>
    /// Administrative office(s) for the administrative subdivision.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Office", Namespace = "http://hoerstemeier.com/tambon/", IsReference = true)]
    public partial class Office
    {

        private string sloganField;

        private string visionField;

        private Point pointField;

        private ThaiAddress addressField;

        private List<MyUri> urlField;

        private SocialWebLinks socialwebField;

        private OfficialList officialsField;

        private List<CouncilTerm> councilField;

        private List<OldLocation> oldlocationsField;

        private OfficeType typeField;

        private bool obsoleteField;

        private bool obsoleteFieldSpecified;

        private string commentField;

        /// <summary>
        /// Creates a new instance of Office.
        /// </summary>
        public Office()
        {
            this.oldlocationsField = new List<OldLocation>();
            this.councilField = new List<CouncilTerm>();
            this.officialsField = new OfficialList();
            this.socialwebField = new SocialWebLinks();
            this.urlField = new List<MyUri>();
            this.addressField = new ThaiAddress();
        }

        /// <summary>
        /// Slogan (คำขวัญ) of the office.
        /// </summary>
        /// <value>
        /// The slogan.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string slogan
        {
            get
            {
                return this.sloganField;
            }
            set
            {
                this.sloganField = value;
            }
        }

        /// <summary>
        /// Vision statement (วิสัยทัศน์) of the office.
        /// </summary>
        /// <value>
        /// The vision.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vision
        {
            get
            {
                return this.visionField;
            }
            set
            {
                this.visionField = value;
            }
        }

        /// <summary>
        /// Location of office, pointing approximately at the main entrance.
        /// </summary>
        /// <value>
        /// The Point.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.w3.org/2003/01/geo/wgs84_pos#", Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Point Point
        {
            get
            {
                return this.pointField;
            }
            set
            {
                this.pointField = value;
            }
        }

        /// <summary>
        /// Postal address of the office.
        /// </summary>
        /// <value>
        /// The address.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThaiAddress address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <summary>
        /// Website of the office, including former websites with the appropriate status.
        /// </summary>
        /// <value>
        /// The url.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute("url", Order = 4)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<MyUri> url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <summary>
        /// Links to the social web sites maintained by the office.
        /// </summary>
        /// <value>
        /// The socialweb.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SocialWebLinks socialweb
        {
            get
            {
                return this.socialwebField;
            }
            set
            {
                this.socialwebField = value;
            }
        }

        /// <summary>
        /// List of office leaders.
        /// </summary>
        /// <value>
        /// The officials.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OfficialList officials
        {
            get
            {
                return this.officialsField;
            }
            set
            {
                this.officialsField = value;
            }
        }

        /// <summary>
        /// List of council terms.
        /// </summary>
        /// <value>
        /// The council.
        /// </value>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("term", IsNullable = false)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<CouncilTerm> council
        {
            get
            {
                return this.councilField;
            }
            set
            {
                this.councilField = value;
            }
        }

        /// <summary>
        /// List of former office locations.
        /// </summary>
        /// <value>
        /// The oldlocations.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute("oldlocations", Order = 8)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<OldLocation> oldlocations
        {
            get
            {
                return this.oldlocationsField;
            }
            set
            {
                this.oldlocationsField = value;
            }
        }

        /// <summary>
        /// Office type of the administrative entity.
        /// </summary>
        /// <value>
        /// The type.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OfficeType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <summary>
        /// Office of an administrative entity no longer existing.
        /// </summary>
        /// <value>
        /// The obsolete.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool obsolete
        {
            get
            {
                return this.obsoleteField;
            }
            set
            {
                this.obsoleteField = value;
            }
        }

        /// <summary>
        /// Auto generated comment tag to suppress XML code documentation warning.
        /// </summary>
        /// <value>
        /// Auto generated value tag to suppress XML code documentation warning.
        /// </value>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool obsoleteSpecified
        {
            get
            {
                return this.obsoleteFieldSpecified;
            }
            set
            {
                this.obsoleteFieldSpecified = value;
            }
        }

        /// <summary>
        /// Comment for information not fitting in any of the formal fields.
        /// </summary>
        /// <value>
        /// The comment.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
    }

    /// <summary>
    /// Office types for the administrative entities.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hoerstemeier.com/tambon/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://hoerstemeier.com/tambon/", IsNullable = false)]
    public enum OfficeType
    {

        /// <summary>
        /// Province hall (ศาลากลางจังหวัด , Sala Klang Changwat)
        /// </summary>
        ProvinceHall,

        /// <summary>
        /// PAO office (สำนักงานองค์การบริหารส่วนจังหวัด).
        /// </summary>
        PAOOffice,

        /// <summary>
        /// District office (ที่ว่าการอำเภอ, Thi Wa Kan Amphoe; สำนักงานเขต Sam Nak Ngan Khet).
        /// </summary>
        DistrictOffice,

        /// <summary>
        /// Municipality office (สำนักงานเทศบาล, Sam Nak Ngan Thesaban).
        /// </summary>
        MunicipalityOffice,

        /// <summary>
        /// TAO office (สำนักงานองค์การบริหารส่วนตำบล or ที่ว่าการองค์การบริหารส่วนตำบล).
        /// </summary>
        TAOOffice,

        /// <summary>
        /// Office of village headman.
        /// </summary>
        VillageHeadmanOffice,

        /// <summary>
        /// Office of community leader (ที่ทำการชุมชน).
        /// </summary>
        ChumchonOffice,

        /// <summary>
        /// Office of subdistrict headman.
        /// </summary>
        SubdistrictHeadmanOffice,
    }
}